export const reducer = {
  LOADING: "SET_LOADING",
  REFRESH: "SET_REFRESH",
  PROFILE: "SET_PROFILE",
  TOKEN: "SET_TOKEN",
  MENU: "SET_MENU",
  CONFIGAPP: "SET_CONFIGAPP",
  REGISTERDEVICE: "SET_REGISTERDEVICE",
  COUNTTIMEOUT: "SET_COUNTTIMEOUT",
};
